export const CATEGORIAS_INSUMO = [
  'Bolsa Master',
  'Caja Detalle Tortas',
  'Caja Master Tortas',
  'Empaque Primario',
  'Etiqueta Caja',
  'Etiqueta Paquetería',
  'Film Fondo',
  'Film Tapa',
  'Fleje',
  'Fondo Carton Corrugado',
  'Funda de Colageno Embutidos',
  'Grapa',
  'Hilo Amarre',
  'Papel Encerado',
  'Sobre para Etiqueta',
  'Tapa Carton Corrugado',
] as const;

export const UNIDADES_MEDIDA = [
  'BOLSAS',
  'ROLLOS',
  'UND',
  'METROS',
  'PAQUETES',
] as const;

export const UNIDADES_POR_CATEGORIA: Record<string, string[]> = {
  'Bolsa Master': ['BOLSAS'],
  'Caja Detalle Tortas': ['UND'],
  'Caja Master Tortas': ['UND'],
  'Empaque Primario': ['BOLSAS', 'ROLLOS', 'UND'],
  'Etiqueta Caja': ['ROLLOS'],
  'Etiqueta Paquetería': ['ROLLOS'],
  'Film Fondo': ['ROLLOS'],
  'Film Tapa': ['ROLLOS'],
  'Fleje': ['ROLLOS'],
  'Fondo Carton Corrugado': ['UND'],
  'Funda de Colageno Embutidos': ['ROLLOS'],
  'Grapa': ['ROLLOS'],
  'Hilo Amarre': ['UND'],
  'Papel Encerado': ['PAQUETES'],
  'Sobre para Etiqueta': ['BOLSAS'],
  'Tapa Carton Corrugado': ['UND'],
};

export interface Insumo {
  codigo: string;
  descripcion: string;
  categoria: string;
  contenido_por_unidad: number;
  unidad_medida: string;
}

export const CATALOGO_INSUMOS: Insumo[] = [
  {
    codigo: '2724',
    descripcion: 'BOLSA PLASTICA  18 X 30 X 300',
    categoria: 'Bolsa Master',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '3809',
    descripcion: 'BOLSA PLASTICA  18+12 X20X100 IMPRESA "5"',
    categoria: 'Bolsa Master',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '11845',
    descripcion: 'BOLSA PLASTICA  22.75+15 X 25 X125 IMPRESA "5"',
    categoria: 'Bolsa Master',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '15302',
    descripcion: 'BOLSA PLASTICA 22.75+15X25X200 IMPRESA DE COLOR AZUL',
    categoria: 'Bolsa Master',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '17825',
    descripcion: 'CAJA P/TORTA DE CARNE RES NATURAL (BEEF) 2LBS',
    categoria: 'Caja Detalle Tortas',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: '16347',
    descripcion: 'CAJA MASTER P/EMPAQUE DE TORTAS DE HAMBURGUESA.',
    categoria: 'Caja Master Tortas',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: '17505',
    descripcion: 'BOLSA  CRY-O-VAC 11 X 18 (P-HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '7060',
    descripcion: 'BOLSA CRY-O-VAC 10 X 16',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '17423',
    descripcion: 'BOLSA CRY-O-VAC 10 X 26',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '17506',
    descripcion: 'BOLSA CRY-O-VAC 10 X 26 (P-HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '16719',
    descripcion: 'BOLSA CRY-O-VAC 13 X 18',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '3670',
    descripcion: 'BOLSA CRY-O-VAC 14 X 21',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '22077',
    descripcion: 'BOLSA CRY-O-VAC 14 X 22 (P- HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '17663',
    descripcion: 'BOLSA CRY-O-VAC 14 X 24',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '24583',
    descripcion: 'BOLSA CRY-O-VAC 14 X 28 (P-HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '3669',
    descripcion: 'BOLSA CRY-O-VAC 15 X 23',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '7100',
    descripcion: 'BOLSA CRY-O-VAC 16 X 24',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '3811',
    descripcion: 'BOLSA CRY-O-VAC 16 X 30',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '25386',
    descripcion: 'BOLSA CRY-O-VAC 18 X 30',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '3665',
    descripcion: 'BOLSA CRY-O-VAC 7 X 17 (P-HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '24584',
    descripcion: 'BOLSA CRY-O-VAC 7 X 22 (P-HUESO)**',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '17424',
    descripcion: 'BOLSA CRY-O-VAC 7 X 26',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '14091',
    descripcion: 'BOLSA CRY-O-VAC 8 X 26',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '17508',
    descripcion: 'BOLSA CRY-O-VAC 9 X 14 (P-HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '28086',
    descripcion: 'BOLSA CRY-O-VAC 9 X 24 (P-HUESO)',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '10500',
    descripcion: 'BOLSA PLASTICA  14 X 24 X 200',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '2727',
    descripcion: 'BOLSA PLASTICA  9 X 14 X 90',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '10501',
    descripcion: 'BOLSA PLASTICA 11 X 14 X 200',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '21439',
    descripcion: 'BOLSA PLASTICA TRANSP 12 X 16 /250  IMPRESA.',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '14224',
    descripcion: 'FUNDA PLASTICA P/CARNE MOLIDA ECONOMICA SALMON 85MM',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 31,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '16192',
    descripcion: 'FUNDA PLASTICA P/CARNE MOLIDA ESPECIAL',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 31,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '16191',
    descripcion: 'FUNDA PLASTICA P/CARNE MOLIDA PREMIUM SUPER',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 31,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '25041',
    descripcion: 'FUNDA PLASTICA SALMON 85MM CHORIZO CRIOLLO CON PICANTE CORRUGADA 227G.',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 30,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '25042',
    descripcion: 'FUNDA PLASTICA SALMON 85MM CHORIZO CRIOLLO CON PICANTE CORRUGADA 454G.',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 30,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '25043',
    descripcion: 'FUNDA PLASTICA SALMON 85MM CHORIZO CRIOLLO CORRUGADA 227G.',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 30,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '25044',
    descripcion: 'FUNDA PLASTICA SALMON 85MM CHORIZO CRIOLLO CORRUGADA 454G.',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 30,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '2722',
    descripcion: 'LAMINA  20 X 26 X 100 IMPRESO  "5"',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: '2724',
    descripcion: 'BOLSA PLASTICA  18 X 30 X 300',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: 'PENDIENTE',
    descripcion: 'Varias bolsas',
    categoria: 'Empaque Primario',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: '27808',
    descripcion: 'ETIQUETA ADHESIVA R-22 TD RECTANGULAR',
    categoria: 'Etiqueta Caja',
    contenido_por_unidad: 1000,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '9883',
    descripcion: 'ETIQUETAS P/CODIGO DE BARRA 3"X 3" R-11',
    categoria: 'Etiqueta Caja',
    contenido_por_unidad: 1000,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '28266',
    descripcion: 'ETIQUETA CHORIZO PARRILLERO ALEMAN',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '28263',
    descripcion: 'ETIQUETA CHORIZO PARRILLERO ARGENTINO',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '28264',
    descripcion: 'ETIQUETA CHORIZO PARRILLERO CRIOLLO',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '28265',
    descripcion: 'ETIQUETA CHORIZO PARRILLERO ESPAÑOL',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '23943',
    descripcion: 'ETIQUETA ADHESIVA   ROJA R-224',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '23944',
    descripcion: 'ETIQUETA ADHESIVA SIGNATURE NEGRA R-224',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '30270',
    descripcion: 'ETIQUETA BOPP R-68',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '17642',
    descripcion: 'ETIQUETAS P/CODIGO BARRA R-15 BOPP TERMICO 13.7 X 7.65, CENTRO DE 1-1/2" (550)',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 550,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '24094',
    descripcion: 'ETIQUETAS V-359 N. CARNIC SIGNATURE (ROLLO)',
    categoria: 'Etiqueta Paquetería',
    contenido_por_unidad: 1500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '7661',
    descripcion: 'FILM PLASTICO  TRANSPARENTE LISO 423X180 MICRAS',
    categoria: 'Film Fondo',
    contenido_por_unidad: 400,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '27128',
    descripcion: 'FILM TAPA 215ΜCRA  X 406MM NEGRO C/LOGO NCA',
    categoria: 'Film Tapa',
    contenido_por_unidad: 300,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '29664',
    descripcion: 'FILM TAPA 215ΜCRA  X 412MM NEGRO C/LOGO NCA',
    categoria: 'Film Tapa',
    contenido_por_unidad: 300,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '4600',
    descripcion: 'SUNCHO 3/8"X 12,000 PIE (3,657 MT)',
    categoria: 'Fleje',
    contenido_por_unidad: 3657,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: 'Varios',
    descripcion: 'TAPA KRAFT 15',
    categoria: 'Tapa Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'TAPA KRAFT 30',
    categoria: 'Tapa Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'TAPA KRAFT 60',
    categoria: 'Tapa Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'TAPA KRAFT 60 ALTA',
    categoria: 'Tapa Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'TAPA SIGANTURE 30',
    categoria: 'Tapa Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'TAPA SIGNATURE  60 ALTA',
    categoria: 'Tapa Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: '15284',
    descripcion: 'FUNDA DE COLAGENO COMESTIBLE ( ROLLO 274  MTS )',
    categoria: 'Funda de Colageno Embutidos',
    contenido_por_unidad: 274,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '15946',
    descripcion: 'CLIPS DE ALUMINIO HC25-2710 T ( ROLLO 9,500 UND )',
    categoria: 'Grapa',
    contenido_por_unidad: 9500,
    unidad_medida: 'ROLLOS',
  },
  {
    codigo: '3712',
    descripcion: 'MECATE MACEN DE 1/8  (HILO FIBRILADO # 20)',
    categoria: 'Hilo Amarre',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: '15791',
    descripcion: 'PAPEL ENCERADO P/HAMBURGUESA DE 4.25" (PQT)',
    categoria: 'Papel Encerado',
    contenido_por_unidad: 778,
    unidad_medida: 'PAQUETES',
  },
  {
    codigo: '7918',
    descripcion: 'BOLSA P/ETIQUETAS 4.5 X 6.5 X 300',
    categoria: 'Sobre para Etiqueta',
    contenido_por_unidad: 1,
    unidad_medida: 'BOLSAS',
  },
  {
    codigo: 'Varios',
    descripcion: 'FONDO KRAFT 15',
    categoria: 'Fondo Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'FONDO KRAFT 30',
    categoria: 'Fondo Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'FONDO KRAFT 60',
    categoria: 'Fondo Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
  {
    codigo: 'Varios',
    descripcion: 'FONDO KRAFT 60 ALTA',
    categoria: 'Fondo Carton Corrugado',
    contenido_por_unidad: 1,
    unidad_medida: 'UND',
  },
];
